2018-04-22 17:58:45,464 DEBUG - Id(0) - 62
2018-04-22 17:58:45,496 DEBUG - Id(1) - 97
2018-04-22 17:58:45,500 DEBUG - Id(2) - 19
2018-04-22 17:58:45,500 DEBUG - Id(3) - 77
2018-04-22 17:58:45,501 DEBUG - Id(4) - 61
2018-04-22 17:58:45,501 DEBUG - Id(5) - 46
2018-04-22 17:58:45,501 DEBUG - Id(6) - 36
2018-04-22 17:58:45,502 DEBUG - Id(7) - 35
2018-04-22 17:58:45,502 DEBUG - Id(8) - 105
2018-04-22 17:58:45,502 DEBUG - Id(9) - 100
2018-04-22 17:58:45,503 WARN  - TEST WARN
2018-04-22 17:58:45,504 ERROR - TEST ERROR
2018-04-22 17:58:45,509 DEBUG - 20 / 2 = 10
2018-04-22 17:58:45,510 DEBUG - 9 / 0 = Infinity
2018-04-22 18:00:43,468 DEBUG - Id(0) - 13
2018-04-22 18:00:43,500 DEBUG - Id(1) - 8
2018-04-22 18:00:43,501 DEBUG - Id(2) - 94
2018-04-22 18:00:43,501 DEBUG - Id(3) - 86
2018-04-22 18:00:43,501 DEBUG - Id(4) - 44
2018-04-22 18:00:43,501 DEBUG - Id(5) - 91
2018-04-22 18:00:43,502 DEBUG - Id(6) - 53
2018-04-22 18:00:43,502 DEBUG - Id(7) - 74
2018-04-22 18:00:43,502 DEBUG - Id(8) - 18
2018-04-22 18:00:43,503 DEBUG - Id(9) - 57
2018-04-22 18:00:43,503 WARN  - TEST WARN
2018-04-22 18:00:43,505 ERROR - TEST ERROR
2018-04-22 18:00:43,510 DEBUG - 20 / 2 = 10
2018-04-22 18:00:43,511 DEBUG - 9 / 0 = Infinity
2018-04-22 18:02:04,996 DEBUG - Id(0) - 87
2018-04-22 18:02:05,026 DEBUG - Id(1) - 59
2018-04-22 18:02:05,026 DEBUG - Id(2) - 62
2018-04-22 18:02:05,027 DEBUG - Id(3) - 74
2018-04-22 18:02:05,027 DEBUG - Id(4) - 51
2018-04-22 18:02:05,028 DEBUG - Id(5) - 20
2018-04-22 18:02:05,028 DEBUG - Id(6) - 84
2018-04-22 18:02:05,028 DEBUG - Id(7) - 55
2018-04-22 18:02:05,029 DEBUG - Id(8) - 79
2018-04-22 18:02:05,029 DEBUG - Id(9) - 98
2018-04-22 18:02:05,030 WARN  - TEST WARN
2018-04-22 18:02:05,031 ERROR - TEST ERROR
2018-04-22 18:02:05,037 DEBUG - 20 / 2 = 10
2018-04-22 18:02:05,455 ERROR - Exception - System.Exception: Div by zero
   at Log4Net.NetCore.Example.Program.<Div>d__10.MoveNext() in D:\Roman\Log4Net.NetCore.Example\Log4Net.NetCore.Example\Program.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Log4Net.NetCore.Example.Program.<DoProgram>d__9.MoveNext() in D:\Roman\Log4Net.NetCore.Example\Log4Net.NetCore.Example\Program.cs:line 43
